FROM golang:alpine AS build-env
WORKDIR ./
ADD . main.go
RUN go build -o promregator-discovery
ENTRYPOINT ./promregator-discovery

# final stage
FROM alpine
WORKDIR ./
COPY --from=build-env ./promregator-discovery ./
ENTRYPOINT ./promregator-discovery