global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'promregator-discovery'
    file_sd_configs:
      - files:
          - /promregator_discovery/promregator_discovery.json

  - job_name: 'promregator'
    scrape_interval: 30s
    scrape_timeout: 20s
    scheme: http
    metrics_path: /promregatorMetrics
    static_configs:
      - targets:
          - promregator:8080
        labels:
          zone: local
